In [3]:
import pandas as pd
import numpy as np
ob=pd.Series([2,3,4,5],index=["a","b","c","d"])
ob

a    2
b    3
c    4
d    5
dtype: int64

In [8]:
display(ob.index)
ob.values

Index(['a', 'b', 'c', 'd'], dtype='object')

array([2, 3, 4, 5], dtype=int64)

In [9]:
"d" in ob

True

In [10]:
ob["b"]

3

In [11]:
ob[3]

5

In [13]:
ob[[1,3]]

b    3
d    5
dtype: int64

In [14]:
ob[["a","c"]]

a    2
c    4
dtype: int64

In [16]:
ob[ob>2]

b    3
c    4
d    5
dtype: int64

In [17]:
ob>2

a    False
b     True
c     True
d     True
dtype: bool

In [18]:
ob[:3]

a    2
b    3
c    4
dtype: int64

In [20]:
ob.loc["b":"d"]

b    3
c    4
d    5
dtype: int64

In [22]:
a=np.array([23,43,54,43,32])
b=np.array(["a","e","i","o","u"])
ob1=pd.Series(a,index=b)
ob1

a    23
e    43
i    54
o    43
u    32
dtype: int32

In [24]:
dic={"name":"simra","age":17,"fees":np.nan,"roll no":201}
ob2=pd.Series(dic)
ob2

name       simra
age           17
fees         NaN
roll no      201
dtype: object

In [25]:
pd.isnull(ob2)

name       False
age        False
fees        True
roll no    False
dtype: bool

In [26]:
pd.notnull(ob2)

name        True
age         True
fees       False
roll no     True
dtype: bool

 # DataFrame

In [48]:
fruit=pd.Series(["apple","banana","oranges","grapes"])
comp=pd.Series(["healthy","delicious","juicy","tasty"])
listy={"fruits":fruit,"complement":comp}
fruits_frame=pd.DataFrame(listy)
fruits_frame

fruits complement
0    apple    healthy
1   banana  delicious
2  oranges      juicy
3   grapes      tasty

In [52]:
fruits_frame.index

RangeIndex(start=0, stop=4, step=1)

In [54]:
fruits_frame.values

array([['apple', 'healthy'],
       ['banana', 'delicious'],
       ['oranges', 'juicy'],
       ['grapes', 'tasty']], dtype=object)

In [55]:
fruits_frame.columns

Index(['fruits', 'complement'], dtype='object')

In [61]:
np.random.seed(2345)
test=pd.DataFrame(np.random.randn(7,4),columns=["c1","c2","c3","c4"],index=["r1","r2","r3","r4","r5","r6","r7"])
test

c1        c2        c3        c4
r1 -0.951299  1.768772 -1.141827  0.710755
r2  0.510951  1.149029 -0.538460 -0.736645
r3 -0.075996  0.848818  0.649783 -0.571212
r4 -0.914158 -0.123520  0.281634  0.795612
r5  0.179394  1.202007  0.371815 -0.290084
r6  0.383571  0.602971 -0.191310 -2.012230
r7 -0.324396  0.244547  0.017233  0.128929

In [67]:
test.head()

c1        c2        c3        c4
r1 -0.951299  1.768772 -1.141827  0.710755
r2  0.510951  1.149029 -0.538460 -0.736645
r3 -0.075996  0.848818  0.649783 -0.571212
r4 -0.914158 -0.123520  0.281634  0.795612
r5  0.179394  1.202007  0.371815 -0.290084

In [68]:
test.tail()

c1        c2        c3        c4
r3 -0.075996  0.848818  0.649783 -0.571212
r4 -0.914158 -0.123520  0.281634  0.795612
r5  0.179394  1.202007  0.371815 -0.290084
r6  0.383571  0.602971 -0.191310 -2.012230
r7 -0.324396  0.244547  0.017233  0.128929

In [66]:
dicty={"country":["pakistan","japan","london","dubai"],"year":[2012,2013,2019,2018],"population":["1M","2M","3M","4M"]}
df1=pd.DataFrame(dicty,index=["d1","d2","d3","d4"])
df1

country  year population
d1  pakistan  2012         1M
d2     japan  2013         2M
d3    london  2019         3M
d4     dubai  2018         4M

In [69]:
df1.head(n=3)

country  year population
d1  pakistan  2012         1M
d2     japan  2013         2M
d3    london  2019         3M

In [70]:
df1["country"]

d1    pakistan
d2       japan
d3      london
d4       dubai
Name: country, dtype: object

In [78]:
df1.year

d1    2012
d2    2013
d3    2019
d4    2018
Name: year, dtype: int64

In [79]:
df1[["country","population"]]

country population
d1  pakistan         1M
d2     japan         2M
d3    london         3M
d4     dubai         4M

In [82]:
df1.iloc[1:3]

country  year population
d2   japan  2013         2M
d3  london  2019         3M

In [84]:
df1.loc["d1"]

country       pakistan
year              2012
population          1M
Name: d1, dtype: object

In [86]:
df1.loc[["d1","d3"]]

country  year population
d1  pakistan  2012         1M
d3    london  2019         3M

In [88]:
df1.loc["d1":"d3"]

country  year population
d1  pakistan  2012         1M
d2     japan  2013         2M
d3    london  2019         3M

In [89]:
df1.loc["d1"]["year"]

2012

In [90]:
dicty={"country":["pakistan","japan","london","dubai"],"year":[2012,2013,2019,2018],"population":["1M","2M","3M","4M"]}
df2=pd.DataFrame(dicty,index=["d1","d2","d3","d4"],columns=["country","population","year","earning"])
df2

country population  year earning
d1  pakistan         1M  2012     NaN
d2     japan         2M  2013     NaN
d3    london         3M  2019     NaN
d4     dubai         4M  2018     NaN

In [91]:
len(df2)

4

In [96]:
val=np.arange(1,5)
val

array([1, 2, 3, 4])

In [97]:
df2["earning"]=val
df2

country population  year  earning
d1  pakistan         1M  2012        1
d2     japan         2M  2013        2
d3    london         3M  2019        3
d4     dubai         4M  2018        4

In [98]:
df2["earning"]=10000
df2

country population  year  earning
d1  pakistan         1M  2012    10000
d2     japan         2M  2013    10000
d3    london         3M  2019    10000
d4     dubai         4M  2018    10000

In [101]:
l=len(df2)
print(l)
val=np.arange(l)
print(val)
df2["earning"]=val
df2

4
[0 1 2 3]


country population  year  earning
d1  pakistan         1M  2012        0
d2     japan         2M  2013        1
d3    london         3M  2019        2
d4     dubai         4M  2018        3

In [6]:
import pandas as pd
import numpy as np

In [7]:
df=pd.DataFrame(np.random.randn(4,3),index=["a","b","c","d"],columns=list("ABC"))
display(df)

A         B         C
a  0.836389  0.037156 -0.692284
b -0.763740  1.161542 -0.433159
c -0.304678 -0.135686  0.575285
d  0.724964  0.465647 -0.281088

In [8]:
display(df.sum())
display(df.sum(axis="columns"))
display(df.sum(axis=1))

A    0.492935
B    1.528660
C   -0.831245
dtype: float64

a    0.181262
b   -0.035356
c    0.134921
d    0.909524
dtype: float64

a    0.181262
b   -0.035356
c    0.134921
d    0.909524
dtype: float64

In [9]:
display("min value = ",df["A"].min())
display("max value = ",df["A"].max())
display(df["A"].max()-df["A"].min())

'min value = '

-0.7637396212808635

'max value = '

0.8363889867876362

1.6001286080684998

In [10]:
display(df.min())
display(df.max())

A   -0.763740
B   -0.135686
C   -0.692284
dtype: float64

A    0.836389
B    1.161542
C    0.575285
dtype: float64

In [11]:
display(df.min(axis=1))
display(df.max(axis=1))

a   -0.692284
b   -0.763740
c   -0.304678
d   -0.281088
dtype: float64

a    0.836389
b    1.161542
c    0.575285
d    0.724964
dtype: float64

In [12]:
function=df.abs()
function

A         B         C
a  0.836389  0.037156  0.692284
b  0.763740  1.161542  0.433159
c  0.304678  0.135686  0.575285
d  0.724964  0.465647  0.281088

In [15]:
import pandas as pd
import numpy as np
d=lambda x:x.max()-x.min()
A=function.apply(d)
display(A)

A    0.531711
B    1.124386
C    0.411196
dtype: float64

In [18]:
def d(x):
    maximum=x.max()
    minimum=x.min()
    return pd.Series(maximum-minimum)
B=function.apply(d)
display(B)

A         B         C
0  0.531711  1.124386  0.411196

In [19]:
def d(x):
    return pd.Series(x.max()-x.min())
C=function.apply(d)
display(C)
    

A         B         C
0  0.531711  1.124386  0.411196

In [24]:
df2=pd.DataFrame(np.arange(8).reshape((2,4)),columns=list("DCBA"),index=["two","one"])
df2

D  C  B  A
two  0  1  2  3
one  4  5  6  7

In [31]:
Q=df2.sort_index()
display(Q)

display(df2.sort_index(axis=1))

D  C  B  A
one  4  5  6  7
two  0  1  2  3

A  B  C  D
two  3  2  1  0
one  7  6  5  4

In [32]:
display(Q.sort_values(by="A"))

D  C  B  A
two  0  1  2  3
one  4  5  6  7

In [33]:
display(df2.rank())

D    C    B    A
two  1.0  1.0  1.0  1.0
one  2.0  2.0  2.0  2.0

In [34]:
display(df2.rank(ascending=False))

D    C    B    A
two  2.0  2.0  2.0  2.0
one  1.0  1.0  1.0  1.0

In [36]:
display(df2.rank(axis=1,ascending=False))

D    C    B    A
two  4.0  3.0  2.0  1.0
one  4.0  3.0  2.0  1.0

In [37]:
display(df2.rank(axis=1))

D    C    B    A
two  1.0  2.0  3.0  4.0
one  1.0  2.0  3.0  4.0

In [38]:
dfn=pd.DataFrame([[2.3,np.nan],[2.3,4],[np.nan,np.nan],[4,3]],index=list("ABCD"),columns=["one","two"])
dfn

one  two
A  2.3  NaN
B  2.3  4.0
C  NaN  NaN
D  4.0  3.0

In [46]:
display(dfn["one"].unique())
display(dfn["two"].unique())


array([2.3, nan, 4. ])

array([nan,  4.,  3.])

In [49]:
display(dfn["one"].value_counts())

2.3    2
4.0    1
Name: one, dtype: int64

In [52]:
display(dfn["one"].count())
display(dfn["two"].count())

3

2

In [1]:
import pandas as pd
import numpy as np


In [2]:
fs1=pd.DataFrame(np.arange(9).reshape((3,3)),index=["A","B","C"],columns=list("xyz"))
fs1

x  y  z
A  0  1  2
B  3  4  5
C  6  7  8

In [3]:
fs2=pd.DataFrame(np.arange(16).reshape((4,4)),index=["A","B","C","D"],columns=list("wxyz"))
fs2

w   x   y   z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [4]:
fs3=fs1+fs2
fs3

w     x     y     z
A NaN   1.0   3.0   5.0
B NaN   8.0  10.0  12.0
C NaN  15.0  17.0  19.0
D NaN   NaN   NaN   NaN

In [5]:
fs3.loc["B","y"]=np.nan

In [6]:
fs3

w     x     y     z
A NaN   1.0   3.0   5.0
B NaN   8.0   NaN  12.0
C NaN  15.0  17.0  19.0
D NaN   NaN   NaN   NaN

In [7]:
fs3.loc[["A","B"],["x","y"]]

x    y
A  1.0  3.0
B  8.0  NaN

In [9]:
fs3.iloc[:3,0:3]

w     x     y
A NaN   1.0   3.0
B NaN   8.0   NaN
C NaN  15.0  17.0

In [19]:
fs4=fs3.add(1,fill_value=2)
fs4

w     x     y     z
A  3.0   2.0   4.0   6.0
B  3.0   9.0   3.0  13.0
C  3.0  16.0  18.0  20.0
D  3.0   3.0   3.0   3.0

In [20]:
fs5=fs3.add(0,fill_value=0)
fs5

w     x     y     z
A  0.0   1.0   3.0   5.0
B  0.0   8.0   0.0  12.0
C  0.0  15.0  17.0  19.0
D  0.0   0.0   0.0   0.0

In [29]:
series=fs5.iloc[0]
display(series,series.index,series.values,fs5-series)

w    0.0
x    1.0
y    3.0
z    5.0
Name: A, dtype: float64

Index(['w', 'x', 'y', 'z'], dtype='object')

array([0., 1., 3., 5.])

w     x     y     z
A  0.0   0.0   0.0   0.0
B  0.0   7.0  -3.0   7.0
C  0.0  14.0  14.0  14.0
D  0.0  -1.0  -3.0  -5.0

In [31]:
f1=fs5.drop("D")
f1

w     x     y     z
A  0.0   1.0   3.0   5.0
B  0.0   8.0   0.0  12.0
C  0.0  15.0  17.0  19.0

In [33]:
f2=fs5.drop("w",axis="columns")
f2

x     y     z
A   1.0   3.0   5.0
B   8.0   0.0  12.0
C  15.0  17.0  19.0
D   0.0   0.0   0.0

In [49]:
data=pd.DataFrame(np.random.randn(4,4),index=["artificial","intelligence","deep learning","web development"]
                  ,columns=["one","two","three","four"])
data

one       two     three      four
artificial      -0.194339 -1.459437  0.327493  0.484051
intelligence    -0.119102 -0.798296  1.210679 -0.143515
deep learning    1.716685 -0.191063 -1.447242  0.488018
web development  0.012527  0.242153 -0.017161 -0.375146

In [53]:
data1=data.index.map(str.upper)
data1

Index(['ARTIFICIAL', 'INTELLIGENCE', 'DEEP LEARNING', 'WEB DEVELOPMENT'], dtype='object')

In [54]:
data

one       two     three      four
artificial      -0.194339 -1.459437  0.327493  0.484051
intelligence    -0.119102 -0.798296  1.210679 -0.143515
deep learning    1.716685 -0.191063 -1.447242  0.488018
web development  0.012527  0.242153 -0.017161 -0.375146

In [56]:
dat=data.rename(index=str.title,columns=str.upper)
dat

ONE       TWO     THREE      FOUR
Artificial      -0.194339 -1.459437  0.327493  0.484051
Intelligence    -0.119102 -0.798296  1.210679 -0.143515
Deep Learning    1.716685 -0.191063 -1.447242  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [61]:
dat.rename(index={"Artificial":"Machine"},columns={"FOUR":"FIVE"})

ONE       TWO     THREE      FIVE
Machine         -0.194339 -1.459437  0.327493  0.484051
Intelligence    -0.119102 -0.798296  1.210679 -0.143515
Deep Learning    1.716685 -0.191063 -1.447242  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [62]:
dat.describe()

ONE       TWO     THREE      FOUR
count  4.000000  4.000000  4.000000  4.000000
mean   0.353943 -0.551661  0.018442  0.113352
std    0.912509  0.740508  1.105507  0.440607
min   -0.194339 -1.459437 -1.447242 -0.375146
25%   -0.137911 -0.963581 -0.374681 -0.201423
50%   -0.053287 -0.494679  0.155166  0.170268
75%    0.438566 -0.082759  0.548289  0.485043
max    1.716685  0.242153  1.210679  0.488018

In [65]:
dat.iloc[0:3,1:3]=np.nan
dat

ONE       TWO     THREE      FOUR
Artificial      -0.194339       NaN       NaN  0.484051
Intelligence    -0.119102       NaN       NaN -0.143515
Deep Learning    1.716685       NaN       NaN  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [73]:
display(dat.dropna())
display(dat.dropna(axis=1))
display(dat.dropna(thresh=2))

ONE       TWO     THREE      FOUR
Web Development  0.012527  0.242153 -0.017161 -0.375146

ONE      FOUR
Artificial      -0.194339  0.484051
Intelligence    -0.119102 -0.143515
Deep Learning    1.716685  0.488018
Web Development  0.012527 -0.375146

ONE       TWO     THREE      FOUR
Artificial      -0.194339       NaN       NaN  0.484051
Intelligence    -0.119102       NaN       NaN -0.143515
Deep Learning    1.716685       NaN       NaN  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [88]:
date=dat.replace(np.nan,5)
date

ONE       TWO     THREE      FOUR
Artificial      -0.194339  5.000000  5.000000  0.484051
Intelligence    -0.119102  5.000000  5.000000 -0.143515
Deep Learning    1.716685  5.000000  5.000000  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [77]:
dat.fillna(20)

ONE        TWO      THREE      FOUR
Artificial      -0.194339  20.000000  20.000000  0.484051
Intelligence    -0.119102  20.000000  20.000000 -0.143515
Deep Learning    1.716685  20.000000  20.000000  0.488018
Web Development  0.012527   0.242153  -0.017161 -0.375146

In [78]:
dat.fillna({"TWO":"hello","THREE":"world"})

ONE       TWO      THREE      FOUR
Artificial      -0.194339     hello      world  0.484051
Intelligence    -0.119102     hello      world -0.143515
Deep Learning    1.716685     hello      world  0.488018
Web Development  0.012527  0.242153 -0.0171606 -0.375146

In [82]:
dat.fillna({"Deep Learning":"hello"})

ONE       TWO     THREE      FOUR
Artificial      -0.194339       NaN       NaN  0.484051
Intelligence    -0.119102       NaN       NaN -0.143515
Deep Learning    1.716685       NaN       NaN  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [86]:
dat.fillna(method="ffill",axis=1)

ONE       TWO     THREE      FOUR
Artificial      -0.194339 -0.194339 -0.194339  0.484051
Intelligence    -0.119102 -0.119102 -0.119102 -0.143515
Deep Learning    1.716685  1.716685  1.716685  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [87]:
dat.fillna(method="bfill")

ONE       TWO     THREE      FOUR
Artificial      -0.194339  0.242153 -0.017161  0.484051
Intelligence    -0.119102  0.242153 -0.017161 -0.143515
Deep Learning    1.716685  0.242153 -0.017161  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [89]:
date

ONE       TWO     THREE      FOUR
Artificial      -0.194339  5.000000  5.000000  0.484051
Intelligence    -0.119102  5.000000  5.000000 -0.143515
Deep Learning    1.716685  5.000000  5.000000  0.488018
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [90]:
date.duplicated(["TWO"])

Artificial         False
Intelligence        True
Deep Learning       True
Web Development    False
dtype: bool

In [91]:
date.duplicated()

Artificial         False
Intelligence       False
Deep Learning      False
Web Development    False
dtype: bool

In [92]:
date.drop_duplicates("TWO")

ONE       TWO     THREE      FOUR
Artificial      -0.194339  5.000000  5.000000  0.484051
Web Development  0.012527  0.242153 -0.017161 -0.375146

In [93]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Artificial to Web Development
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ONE     4 non-null      float64
 1   TWO     1 non-null      float64
 2   THREE   1 non-null      float64
 3   FOUR    4 non-null      float64
dtypes: float64(4)
memory usage: 320.0+ bytes
